spring:
  application:
    name: auth-service
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: booking-app
            client-secret: <client-secret>
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/friendlybooking