spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/friendlybooking
      client:
        registration:
          keycloak:
            client-id: booking-app
            client-secret: DO6LAuTTbK6mzica4jfNxH8AwLGejn7M
            scope: openid
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/friendlybooking