version: '3.8'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.0.1
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev
    ports:
      - 8080:8080
    networks:
      - keycloak-network
    depends_on:
      - postgres

  auth-service:
    build: ./auth-service
    ports:
      - 8081:8081
    networks:
      - keycloak-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - keycloak
    restart: on-failure

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      - keycloak-network
    ports:
      - 5432:5432

networks:
  keycloak-network:
    driver: bridge
