version: '3.8'

services:
  # Keycloak для аутентификации
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: ["start-dev"]
    ports:
      - "8180:8080"
    networks:
      - booking-network
    depends_on:
      - keycloak-db

  # База данных для Keycloak
  keycloak-db:
    image: postgres:14
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak_password
    networks:
      - booking-network
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data

  # Основной сервис приложения
  booking-app:
    build:
      context: ./monolit  # Путь к твоему проекту
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DB_HOST=booking-db
      - DB_PORT=5432
      - DB_NAME=booking
      - DB_USER=booking_user
      - DB_PASSWORD=booking_password
      - BASE_URL=http://localhost:8080
    ports:
      - "8080:8080"
    networks:
      - booking-network
    depends_on:
      - booking-db

  # База данных для основного сервиса
  booking-db:
    image: postgres:14
    environment:
      - POSTGRES_DB=booking
      - POSTGRES_USER=booking_user
      - POSTGRES_PASSWORD=booking_password
    networks:
      - booking-network
    volumes:
      - booking-db-data:/var/lib/postgresql/data

volumes:
  keycloak-db-data:
  booking-db-data:

networks:
  booking-network:
