server:
  port: 8080

spring:
  application:
    name: booking-app

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: booking-app
            client-secret: "m7biPyVyCTvcGj6QeKqe0JR8FhfYjNgN"
            authorization-grant-type: authorization_code
            redirect-uri: "${BASE_URL}/login/oauth2/code/keycloak"
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/realms/friendlybooking

  thymeleaf:
    cache: false
